links:
- text: 'top'
  href: '/?page=top'
- text: '開発日誌（ブログ）'
  href: '/?post'
- text: '外部サイト'
  href: './'
  sublinks:
  - text: '旧サイト'
    href: 'http://test.usptomo.com/'
  - text: '作者ブログ'
    href: 'https://b.ueda.tech/'
sociallinks:
- icon: 'fa-twiter-square'
  href: 'https://twitter.com/aswzjd'
