links:
- text: 'トップページ'
  href: '/?page=top'
- text: 'このサイトについて'
  href: '/?page=about'
- text: 'メニュー'
  href: './'
  sublinks:
  - text: '工事中'
    href: './'
  - text: '工事中'
    href: './'
sociallinks:
- icon: 'fa-twitter-square'
  href: 'https://twitter.com/aswzjd'
