protocol: 'https:'
host: 'shirokuma-tech.com'
sitetitle: 'しろくまの雑記帳'
sitesubtitle: '個人的な備忘録です。'
links:
- text: 'このサイトについて'
  href: '/?page=about'
- text: 'メニュー'
  href: './'
  sublinks:
  - text: '工事中'
    href: './'
  - text: '工事中'
    href: './'
sociallinks:
- icon: 'fa-twitter-square'
  href: 'https://twitter.com/aswzjd'
